apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8shpc-mutating-webhook-dep
  namespace: k8shpc-ns
spec:
  selector:
    matchLabels:
      app: k8shpc-mutating-webhook
  template:
    metadata:
      labels:
        app: k8shpc-mutating-webhook
    spec:
#      serviceAccountName: k8shpc-sa
      containers:
        - image: cerit.io/cerit/k8shpc:27-10-2022-1-editable
          command:
            - "/bin/sh"
            - "-c"
            - "while true; do /usr/local/bin/k8shpc-mutating-webhook -ext_mem=10686180622336 -ext_cpu=504 -ext_gpu=4 -k8s_mem=540203466752 -k8s_cpu=64 -k8s_gpu=2; sleep 1; done"
          env:
            - name: "TAG"
              value: "v0.5"
            - name: "IMAGE"
              value: "cerit.io/cerit/geant-proxy"
          readinessProbe:
            httpGet:
              port: 8443
              path: /health
              scheme: HTTPS
            periodSeconds: 10
          name: k8shpc-mutating-pod
          volumeMounts:
            - name: tls
              mountPath: "/etc/tls"
      securityContext:
        runAsUser: 1000
      volumes:
        - name: tls
          secret:
            secretName: k8shpc-mutating-webhook-cert-secret