apiVersion: v1
kind: Service
metadata:
  name: k8shpc-mutating-webhook-svc
  namespace: k8shpc-ns
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: k8shpc-mutating-webhook