apiVersion: v1
kind: Service
metadata:
  name: ${exppodname}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${exppodname}.dyn.cloud.e-infra.cz
    metallb.universe.tf/address-pool: privmuni
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 2222
  selector:
    app: ${exppodname}
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${exppodname}
  finalizers:
  - ${finalizer}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${exppodname}
  template:
    metadata:
      labels:
        app: ${exppodname}
    spec:
      containers:
      - name: ssh-proxy
        command: 
        - /srv/start-sshproxy.sh 
        image: cerit.io/cerit/geant-proxy:v0.5
        imagePullPolicy: IfNotPresent
        securityContext:                                                          
          runAsUser: 1000 
          runAsGroup: 1000
        resources:
          limits:
            cpu: 1
            memory: 256Mi
        ports:
        - containerPort: 2222
        volumeMounts:
        - name: vol-1
          mountPath: ${mnt}
      volumes:
      - name: vol-1
        persistentVolumeClaim:
          claimName: ${pvc}
